#!/bin/bash
#
#

_CORE_CALL_DIR=$(dirname $0)

#
# INCLUDES
#
source ${_CORE_CALL_DIR}/kp_core

#
# INTIALISE
#
OPT_VERBOSE=


#
# FUNCTIONS
#
function usage {
  _EXIT_VAL=${1:-0}

  echo << EOF
  Usage: $0 [-vc]

  Options:
    -v   Show verbose output
    -?   Show this usage
    -V   Show version

  Long Options:
    --verbose     Same as -v
    --help        Same as -?
    --version     Same as -V

  Status:
   -    Available but not checked out
   ?    Checked out but no upstream available.
   S    Synchronised with upstream
   M    Local modifications
EOF

  exit ${_EXIT_VAL};
}

#
# PARSE COMMAND LINE
#

CMD_LINE=$(getopt -n$0 -u --longoptions="verbose version help" "v V ?" $@)
[ ${?} -ne 0 ] && usage 1

set -- ${CMD_LINE}

while [ $# -gt 0 ]
do
  case "$1" in
    -v|--verbose)
      OPT_VERBOSE=1
      ;;
    -V|--version)
      version 0
      ;;
    -h|--help)
      usage 0
      ;;
    --)
      shift
      break
      ;;
    -*)
      usage 1
      ;;
    *)
      break
  esac
  shift
done


#
# MAIN
#

echo "Korora Checkout:"

# load the configuration
for F in $(list_config_available)
do
  load_config ${F}
  [ ${?} -ne 0 ] && continue

  get_sync_status
  [ ${?} -ne 0 ] && continue

  if [ -z ${OPT_VERBOSE} ]
  then
    printf " %s  %-32s\n" ${KP_SYNC_STATE} ${KP_NAME}
  else
    printf " %s  %-32s\t%-8s\t%s\n" ${KP_SYNC_STATE} ${KP_NAME} ${KP_VERSION} ${KP_URL}
  fi
done

