#!/bin/bash
#
# Copyright 2012 "Korora Project" <dev@kororaproject.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the temms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

#
# INTIALISE
#
OPT_VERBOSE=
OPT_LIST=
OPT_USB=
OPT_ISO=1


#
# FUNCTIONS
#
function usage {
  _EXIT_VAL=${1:-0}

  cat << EOF
Usage: $0 release [options]

Options:
  -l,  List available kickstarts to build
  -v   Show verbose output
  -?   Show this usage
  -V   Show version

Long Options:
  --list        Same as -l
  --iso         Build an ISO image [default]
  --usb         Build a USB image
  --verbose     Same as -v
  --help        Same as -?
  --version     Same as -V

EOF

  exit ${_EXIT_VAL};
}

#
# PARSE COMMAND LINE
#

function parse_args {
  CMD_LINE=$(getopt -n$0 -u --longoptions="list iso usb verbose version help" "l v V ?" $@)
  [ ${?} -ne 0 ] && usage 1

  set -- ${CMD_LINE}

  while [ $# -gt 0 ]
  do
    case "$1" in
      -l|--list)
        OPT_LIST=1
        ;;
      --iso)
        OPT_ISO=1
        OPT_USB=
        ;;
      --usb)
        OPT_ISO=
        OPT_USB=1
        ;;
      -v|--verbose)
        OPT_VERBOSE=1
        ;;
      -V|--version)
        version 0
        ;;
      --help)
        usage 0
        ;;
      --)
        shift
        break
        ;;
      -*)
        usage 1
        ;;
      *)
        break
    esac
    shift
  done
}


#
# MAIN
#

function main {
  _info "Initialising Korora Package environment ..."

  # convert working dir is absolute path
  WORKING_DIR=$(readlink -e "${WORKING_DIR}")

  # create working directory
  _info "Preparing: ${WORKING_DIR}"

  if [ ! -d "${WORKING_DIR}" ]
  then
    _info "Creating ..."
    mkdir -p "${WORKING_DIR}/"
  elif [ -n "${OPT_FORCE}" ]
  then
    _info "Already exists. Forcing clean ..."

    rm -rf "${WORKING_DIR}/*"
  else
    _info "Already exists."
  fi

  if [ -w "${WORKING_DIR}" ]
  then
    # show disk usage of working dir
    _DISK_AVAILABLE=$(df -h ${WORKING_DIR} | tail -n 1 | awk '{print $4}')
    _DISK_USAGE=$(du -sh ${WORKING_DIR} | cut -f1)

    _info "${_DISK_USAGE}B used - ${_DISK_AVAILABLE}B remaining"
  else
    _error "Directory is not writable."
  fi
}

