#!/bin/bash
#
# Copyright 2012-2013 "Korora Project" <dev@kororaproject.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the temms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

#
# INTIALISE
#
OPT_VERBOSE=
OPT_USB=
OPT_ISO=1
OPT_CACHE_ONLY=

OPT_RELEASE_VERSION=18
OPT_RELEASE_CODENAME="Flo"
OPT_RELEASE_BASEARCH="x86_64"

#
# PRIVATE FUNCTIONS
#

function _template_inflate {
  _DST_FILE=${1}
  _SRC_FILE=${2}

  if [ -r ${_SRC_FILE} ]
  then
    cp "${_SRC_FILE}" "${_DST_FILE}"
  fi

  # substitute variables
  sed -i -e "s@%%KP_KICKSTART_DIR%%@${WORKING_DIR}/conf/kickstart.d@g" \
         -e "s@%%KP_REPOSITORY%%@file://${WORKING_DIR}/repository@g" \
         -e "s@%%KP_BASEARCH%%@${OPT_RELEASE_BASEARCH}@g" \
         -e "s@%%KP_VERSION%%@${OPT_RELEASE_VERSION}@g" ${_DST_FILE}

  # check for includes in our template
  grep "%include" ${_DST_FILE} | while read I F
  do
    _FI="/tmp/$(basename ${F}).${RANDOM}"

    # replace include with our inflated version
    sed -i "s@$F@${_FI}@" ${_DST_FILE}

    # ensure includes are inflated
    _template_inflate "${_FI}" "${F}"
  done
}

#
# FUNCTIONS
#

function usage {
  _EXIT_VAL=${1:-0}

  cat << EOF
Usage: $0 release [options] [release ... releaseN]

Options:
  -t   Set the release title
  -r   Set the release version
  -n   Set the release codename
  -a   Set the release architecture
  -C   Use cached packages only
  -v   Show verbose output
  -?   Show this usage
  -V   Show version

Long Options:
  --release-title     Same as -t
  --release-version   Same as -r
  --release-codename  Same as -n
  --release-arch      Same as -a
  --cache-only        Same as -C
  --verbose           Same as -v
  --help              Same as -?
  --version           Same as -V

EOF

  exit ${_EXIT_VAL};
}

#
# PARSE COMMAND LINE
#

function parse_args {
  CMD_LINE=$(getopt -n$0 -u --longoptions="title release-version release-codename release-arch verbose cache-only version help" "t r n a C l v V ?" $@)
  [ ${?} -ne 0 ] && usage 1

  set -- ${CMD_LINE}

  while [ $# -gt 0 ]
  do
    case "$1" in
      -t|--title)
        OPT_RELEASE_TITLE="$3"
        ;;
      -r|--release-version)
        OPT_RELEASE_VERSION="$3"
        ;;
      -n|--release-codename)
        OPT_RELEASE_CODENAME="$3"
        ;;
      -a|--release-arch)
        OPT_RELEASE_BASEARCH="$3"
        ;;
      -C|--cache-only)
        OPT_CACHE_ONLY="$3"
        ;;
      -v|--verbose)
        OPT_VERBOSE=1
        ;;
      -V|--version)
        version 0
        ;;
      --help)
        usage 0
        ;;
      --)
        shift
        break
        ;;
      -*)
        usage 1
        ;;
      *)
        break
    esac
    shift
  done

  # remaining arguments are releases
  RELEASES=
  if [ $# -eq 0 ]
  then
    echo "Building all releases ..."
  else
    while [ $# -gt 0 ]
    do
      RELEASES="${RELEASES} $1"
      shift
    done
  fi
}


#
# MAIN
#

function main {
  # must be root to run
  if [ "$(id -u)" -ne 0 ]
  then
    _error "You must be root to build a release ISO."
    exit 1
  fi

  list_kickstart_validate "${RELEASES}"
  if [ ${?} -gt 0 ]
  then

    _OPTS=

    [ ! -z ${OPT_VERBOSE} ] && _OPTS="${_OPTS} --verbose"
    [ ! -z ${OPT_CACHE_ONLY} ] && _OPTS="${_OPTS} --cache-only"

    # build all requested releases
    for R in $(list_kickstart_available "${RELEASES}")
    do

      #
      _info "Preparing to build: $R"
      _info "  - Codename:     ${OPT_RELEASE_CODENAME}"
      _info "  - Version:      ${OPT_RELEASE_VERSION}"
      _info "  - Architecture: ${OPT_RELEASE_BASEARCH}"

      _FILE="korora-${OPT_RELEASE_VERSION}-${OPT_RELEASE_BASEARCH}-${R}-live"

      # create working directory
      _TEMPLATE="/tmp/${R}.ks.${RANDOM}"
      _TEMPLATE_FLATTENED="/tmp/${R}-flattened.ks.${RANDOM}"

      _info "Preparing release template: ${_TEMPLATE}"

      #
      _template_inflate "${_TEMPLATE}" "${WORKING_DIR}/conf/kickstart.d/${R}.ks"

      # flattening template
      _info "Flattening template into: ${_TEMPLATE_FLATTENED}"
      ksflatten -c "${_TEMPLATE}" -o "${_TEMPLATE_FLATTENED}"

      # create the CD
      _info "Creating release ..."
      setarch="$OPT_RELEASE_BASEARCH" livecd-creator ${_OPTS} --config="${_TEMPLATE}" --fslabel="${_FILE}" --title="Korora ${OPT_RELEASE_VERSION}" --product="Korora ${OPT_RELEASE_VERSION} (${OPT_RELEASE_CODENAME})" --cache="${WORKING_RELEASE_CACHE_DIR}" --tmpdir="${WORKING_RELEASE_TMP_DIR}" --logfile="${LOG_FILE}"

      # livemedia-creator --make-iso --ks="${_TEMPLATE_FLATTENED}" --image-name="${_FILE}" --title="Korora ${OPT_RELEASE_VERSION}" --project="Korora ${OPT_RELEASE_VERSION} (${OPT_RELEASE_CODENAME})" --releasever="${OPT_RELEASE_VERSION}" --arch="${OPT_RELEASE_BASEARCH}" --tmp="${WORKING_RELEASE_TMP_DIR}" --logfile="${LOG_FILE}" --no-virt

      # clean up our inflated template file
      #rm -f "${_TEMPLATE}" "${_TEMPLATE_FLATTENED}"
    done
  fi
}
