#!/bin/bash
#
# Copyright 2012 "Korora Project" <dev@kororaproject.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the temms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

VERSION="0.1.0"

#
# PRE-INIT
#
SUB_COMMAND=
CONFIG_FILE=

# assume first parameter to be the subcommand
while [ $# -gt 0 ] && [ -z ${SUB_COMMAND} ]
do
  case "$1" in
    init|--init)
      SUB_COMMAND=init
      ;;
    list|--list)
      SUB_COMMAND=list
      ;;
    build|--build)
      SUB_COMMAND=build
      ;;
    sync|--sync)
      SUB_COMMAND=sync
      ;;
    checkout|--checkout)
      SUB_COMMAND=checkout
      ;;
    release|--release)
      SUB_COMMAND=relese
      ;;
    --config*)
      if [ ${#1} -eq 8 ]
      then
        CONFIG_FILE=$2
        shift
      else
        CONFIG_FILE="${1/--config=/}"
      fi
      ;;
    default)
      ;;
  esac
  shift
done

#
# DEFAULTS
#

[[ -z ${CONFIG_DIR} || ! -d ${CONFIG_DIR} ]] && CONFIG_DIR="/etc/kp"
[[ -z ${LIB_DIR} || ! -d ${LIB_DIR} ]] && LIB_DIR="/usr/share/lib/kp/lib"
[[ -z ${WORKING_DIR} || ! -d ${WORKING_DIR} ]] && WORKING_DIR="/var/lib/kp"
[[ -z ${RELEASE_DIR} || ! -d ${RELEASE_DIR} ]] && RELEASE_DIR="/tmp"
[[ -z ${LOG_DIR} || ! -d ${LOG_DIR} ]] && LOG_DIR="/usr/share/lib/kp/log"
[[ -z ${CONFIG_FILE} || ! -f ${CONFIG_FILE} ]] && CONFIG_FILE="${CONFIG_DIR}/kp.conf"

#
# INCLUDES
#

if [ ! -r "${CONFIG_FILE}" ]
then
  echo "FATAL: No configuration file found."
  exit 1
else
  source "${CONFIG_FILE}"
fi

if [ ! -d "${LIB_DIR}" ]
then
  echo "FATAL: Invalid LIB_DIR defined."
  exit 1
else
  source ${LIB_DIR}/kp_core
fi

if [ ! -d "${LOG_DIR}" ]
then
  echo "FATAL: Invalid LOG_DIR defined."
  exit 1
fi


# expand directories to absolute paths
WORKING_DIR=$(readlink -e "${WORKING_DIR}")
LIB_DIR=$(readlink -e "${LIB_DIR}")
LOG_DIR=$(readlink -e "${LOG_DIR}")
CONFIG_DIR=$(readlink -e "${CONFIG_DIR}")


# build working subdirectories
WORKING_PACKAGES_DIR="${WORKING_DIR}/packages"
WORKING_REPOSITORY_DIR="${WORKING_DIR}/repository"
WORKING_KICKSTART_DIR="${WORKING_DIR}/kickstart"
WORKING_RELEASE_DIR="${WORKING_DIR}/release"
WORKING_RELEASE_CACHE_DIR="${WORKING_DIR}/release/cache"
WORKING_RELEASE_TMP_DIR="${WORKING_DIR}/release/tmp"

SCRIPT=$(basename $0)


DEBUG=1

#
# INCLUDES
#


CALL_PATH=$(dirname $0)

source "${LIB_DIR}/kp_${SUB_COMMAND}" $@

NOW=$(date +'%s')
NOW_LITERAL=$(date '+%Y-%m-%d %H:%M:%S')

LOG_FILE="${LOG_DIR}/kp-${SUB_COMMAND}-${NOW}.log"
touch $LOG_FILE
_log "Logging started: ${NOW_LITERAL}"

# start the main function sourced above
parse_args $@

main
